[project]
name = "agentic-rag-sdk"
version = "0.1.0"
description = "Python SDK for the Agentic RAG API"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[tool.uv]
dev-dependencies = [
    "pytest>=8.0.0",
    "respx>=0.20.0",
]
